// Public API types for the web app.
//
// The openapi-typescript codegen writes to `./openapi.ts` (regenerated by
// `pnpm api:client`). This file re-exports those plus named-type aliases
// for ergonomic consumption (`Placement` rather than `components["schemas"]["Placement"]`).
// Keep aliases sorted by section to mirror `openapi.yaml`.

import type { components } from './openapi.js';

export type { paths, components, operations } from './openapi.js';

type Schemas = components['schemas'];

// ── Auth / identity ────────────────────────────────────────────────────
export type Me = Schemas['Me'];
export type Role = Schemas['Role'];
export type Pagination = Schemas['Pagination'];

// ── Organisations ──────────────────────────────────────────────────────
export type Organisation = Schemas['Organisation'];
export type OrganisationInput = Schemas['OrganisationInput'];

// ── Opportunities ──────────────────────────────────────────────────────
export type Opportunity = Schemas['Opportunity'];
export type OpportunityInput = Schemas['OpportunityInput'];
export type OpportunityStatus = Schemas['OpportunityStatus'];

// ── Applications ───────────────────────────────────────────────────────
export type Application = Schemas['Application'];
export type ApplicationInput = Schemas['ApplicationInput'];
export type ApplicationStatus = Schemas['ApplicationStatus'];
export type ApplicationDecision = Schemas['ApplicationDecision'];
export type Recommendation = Schemas['Recommendation'];

// ── Placements ─────────────────────────────────────────────────────────
export type Placement = Schemas['Placement'];
export type PlacementStatus = Schemas['PlacementStatus'];

// ── Hours ──────────────────────────────────────────────────────────────
export type HoursLogEntry = Schemas['HoursLogEntry'];
export type HoursLogInput = Schemas['HoursLogInput'];
export type HoursLogStatus = Schemas['HoursLogStatus'];
export type HoursLogDecision = Schemas['HoursLogDecision'];

// ── Site visits / evaluations ──────────────────────────────────────────
export type SiteVisitNote = Schemas['SiteVisitNote'];
export type Evaluation = Schemas['Evaluation'];
export type EvaluationType = Schemas['EvaluationType'];

// ── Certificates ───────────────────────────────────────────────────────
export type Certificate = Schemas['Certificate'];
export type CertificateVerification = Schemas['CertificateVerification'];

// ── Ledger / dashboard ─────────────────────────────────────────────────
export type LedgerSummary = Schemas['LedgerSummary'];

// ── Audit log ──────────────────────────────────────────────────────────
export type AuditLogEntry = Schemas['AuditLogEntry'];

// ── Imports ────────────────────────────────────────────────────────────
export type ImportRun = Schemas['ImportRun'];

// Generic paginated-list wrapper. The API returns `{ data, page, pageSize, total }`
// for every list endpoint per CLAUDE.md "All list endpoints paginate" rule.
export type Page<T> = Pagination & { data: T[] };
