// PRC-06 — A4 single-page certificate PDF generator.
//
// Pure-ish: takes a CertificateContent + optional QR PNG buffer and
// returns the PDF bytes. The QR image is generated by qr.ts and passed
// in so this module has no I/O.

import PDFDocument from 'pdfkit';

export interface CertificateContent {
  certificate_id: string;
  student_full_name: string;
  programme_name: string;
  programme_code: string;
  organisation_name: string;
  start_date: Date;
  end_date: Date;
  approved_hours: number;
  composite_rating: number | null;
  issued_at: Date;
}

const A4 = { width: 595.28, height: 841.89 };

function fmtDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

export async function renderCertificatePdf(
  content: CertificateContent,
  qrPng: Buffer | null,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // ── Header ──
    doc
      .fontSize(10)
      .fillColor('#666666')
      .text('Knox Community College', 50, 50, { align: 'left' })
      .fontSize(10)
      .text('Placement & Service Management System', { align: 'left' });

    // ── Title ──
    doc
      .moveDown(2)
      .fontSize(28)
      .fillColor('#000000')
      .text('Certificate of Completion', { align: 'center' });

    doc
      .moveDown(0.5)
      .fontSize(12)
      .fillColor('#666666')
      .text('This document certifies the successful completion of', { align: 'center' });

    // ── Recipient ──
    doc
      .moveDown(1.5)
      .fontSize(22)
      .fillColor('#000000')
      .text(content.student_full_name, { align: 'center' });

    doc
      .moveDown(0.4)
      .fontSize(12)
      .fillColor('#666666')
      .text(`${content.programme_name} (${content.programme_code})`, { align: 'center' });

    // ── Body ──
    const bodyY = 320;
    doc
      .moveTo(50, bodyY - 20)
      .lineTo(A4.width - 50, bodyY - 20)
      .strokeColor('#cccccc')
      .stroke();

    doc
      .fontSize(12)
      .fillColor('#000000')
      .text(`Host organisation: ${content.organisation_name}`, 50, bodyY)
      .moveDown(0.4)
      .text(`Placement period: ${fmtDate(content.start_date)} — ${fmtDate(content.end_date)}`)
      .moveDown(0.4)
      .text(`Approved service hours: ${content.approved_hours}`)
      .moveDown(0.4)
      .text(
        `Composite evaluation: ${
          content.composite_rating === null ? 'n/a' : content.composite_rating.toFixed(2)
        } / 5.00`,
      );

    // ── QR + footer ──
    if (qrPng) {
      doc.image(qrPng, A4.width - 170, A4.height - 220, { width: 120 });
      doc
        .fontSize(8)
        .fillColor('#666666')
        .text('Scan to verify', A4.width - 170, A4.height - 90, { width: 120, align: 'center' });
    }

    // Signature line on the left.
    doc
      .moveTo(50, A4.height - 120)
      .lineTo(280, A4.height - 120)
      .strokeColor('#000000')
      .stroke();
    doc
      .fontSize(10)
      .fillColor('#000000')
      .text('Placement Coordinator', 50, A4.height - 115);

    // Footer
    doc
      .fontSize(8)
      .fillColor('#666666')
      .text(`Certificate ID: ${content.certificate_id}`, 50, A4.height - 60)
      .text(`Issued: ${fmtDate(content.issued_at)}`)
      .text('Verify at /verify/' + content.certificate_id);

    doc.end();
  });
}
